[package]
name = "audis-audio"
description = "Audio device enumeration and capture for Audis."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
audis-common.workspace = true

serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

cpal = "0.18.1"

[dev-dependencies]
serde_json.workspace = true
